app/views/vistas.py
#app/views/vistas.py
from flask import Blueprint, Flask, render_template, request, redirect, url_for, session, flash, jsonify
from app.controllers.controler import registrar_usuarios, obtener_usuarios_paginados, register_cita, obtenerCitas_paginas, obtener_intervalo, actualizar_intervalo, obtener_cita_por_id, actualizar_cita, obtener_usuario_por_id, actualizar_usuario, registrar_usuariosAses
from app.models.modelo import Paciente, Appointment, User, Cita
from app import db
from flask_paginate import Pagination, get_page_parameter
import hashlib
import logging
from passlib.hash import pbkdf2_sha256
from flask_cors import CORS
from datetime import datetime
from app.models.modelo import db, Settings
from functools import wraps
from flask import request, redirect, url_for, session, flash
from werkzeug.security import check_password_hash
from datetime import timedelta


logging.basicConfig(level=logging.DEBUG)

main = Blueprint('main', __name__)

CORS(main)

appointments = {}





def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return render_template('sesionCerrada.html')
        return f(*args, **kwargs)
    return decorated_function


@main.route('/')
def home():
    # Devuelve una plantilla llamada 'index.html'
    return render_template('index.html')

app = Flask(__name__)

# Configuración de la clave secreta
app.secret_key = 'tu_clave_secreta_aqui'

# Configuración del tiempo de vida de la sesión
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=1)

@main.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        
        logging.debug(f"Contraseña ingresada: {password}")
        # Realizar la consulta utilizando el modelo User
        user = User.query.filter_by(username=username).first()
        
        if user:
            # Obtener el salt almacenado
            salt = user.salt
            logging.debug(f"Salt almacenado: {salt}")
            
            # Hash la contraseña ingresada usando SHA-1 con el salt
            password_salted = password.encode('utf-8') + salt.encode('utf-8')
            password_hash = hashlib.sha1(password_salted).hexdigest()
            logging.debug(f"Hash de la contraseña ingresada: {password_hash}")
            
            # Verificar si el hash de la contraseña ingresada coincide con el hash almacenado
            if user.password == password_hash:
                session.permanent = True  # Establecer la sesión como permanente
                session['user_id'] = user.user_id
                session['username'] = user.username
                session['fname'] = user.fname
                session['lname'] = user.lname
                logging.debug(f"Usuario de sesion: {session['fname']}")
                flash('Inicio de sesión exitoso!', 'success')
                return redirect(url_for('main.dashboard'))
        
        # Si la verificación falla, mostrar un mensaje de error
        flash('Credenciales incorrectas. Inténtalo de nuevo.', 'danger')
        return render_template("credencialesError.html")
    
    # Si el método es GET, renderizar la página de inicio de sesión
    return render_template("index.html")

@main.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('username', None)
    session.pop('fname', None)
    session.pop('lname', None)
    # Elimina otros datos de sesión
    flash('Has cerrado sesión')
    return redirect(url_for('main.index'))



@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('view_administrator.html')
    

@main.route('/usuarios')
@login_required
def usuarios():
    page = request.args.get('page', 1, type=int)
    per_page = 10
    group_id = 5  # Define el ID del grupo que deseas filtrar
    paginated_users = obtener_usuarios_paginados(page, per_page, group_id=group_id)
    if paginated_users:
        return render_template('usuarios.html', users=paginated_users)
    else:
        return render_template('usuarios.html', users=[])

@main.route('/citas')
@login_required
def citas():
    return render_template('calendariocitas.html')
          
@main.route('/calendario')
@login_required
def calendario():
    return render_template('calendario.html')

@main.route('/reg_usuarios', methods=['GET', 'POST'])
@login_required
def reg_usuarios():
    logging.debug(f"Formulario de datos recibidos: {request.form}")
    if request.method == 'POST':
        form_data = request.form
        registrar_usuarios(form_data)
        flash('Usuario registrado exitosamente', 'success')
        return redirect(url_for('main.usuarios'))
    return render_template('form_registrousuarios.html')


@main.route('/reg_usuariosAses', methods=['GET', 'POST'])
@login_required
def reg_usuariosAses():
    logging.debug(f"Formulario de datos recibidos: {request.form}")
    if request.method == 'POST':
        form_data = request.form
        registrar_usuariosAses(form_data)
        flash('Usuario registrado exitosamente', 'success')
        return redirect(url_for('main.usuarios'))
    return render_template('formRegisAsesor.html')


@main.route('/reg_citas', methods=['GET', 'POST'])
@login_required
def reg_citas():
    logging.debug(f"Formulario de datos recibidos: {request.form}")
    if request.method == 'POST':
        form_data = request.form.to_dict()
        nueva_cita = register_cita(form_data)
        if nueva_cita:
            flash('Cita registrada exitosamente', 'success')
        else:
            flash('Error al registrar la cita', 'danger')
        return redirect(url_for('main.reg_citas'))
    return render_template('view_administrator.html')



@main.route('/search_user')
@login_required
def search_user():
    query = request.args.get('query')
    if query:
        users = User.query.filter(User.organization.like(f"%{query}%")).all()
        results = [
            {'fname': user.fname, 'lname': user.lname, 'email': user.email, 'organization': user.organization}
            for user in users
        ]
        return jsonify(results=results)
    return jsonify(results=[])


@main.route('/Consul_citas')
@login_required
def Con_Citas():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    paginated_appointments = obtenerCitas_paginas(page, per_page)
    
    if paginated_appointments:
        no_canceladas = [cita for cita in paginated_appointments.items if cita.status_id != 2]
        canceladas = [cita for cita in paginated_appointments.items if cita.status_id == 2]
        citas_ordenadas = no_canceladas + canceladas

        paginated_appointments.items = citas_ordenadas

        return render_template('citas.html', citas=paginated_appointments)
    else:
        return render_template('citas.html', citas=[])

@main.route('/appointments', methods=['POST'])
@login_required
def save_appointment():
    data = request.get_json()
    date = data['date']
    time = data['time']
    appointment = data['appointment']
    
    if date not in appointments:
        appointments[date] = {}
    appointments[date][time] = appointment
    
    return jsonify(success=True)



@main.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if request.method == 'POST':
        nuevo_intervalo = request.form['time-interval']
        actualizar_intervalo(nuevo_intervalo)
        flash('Intervalo de tiempo actualizado con éxito', 'success')
        return redirect(url_for('main.admin'))

    intervalo = obtener_intervalo()
    return render_template('admin_int.html', intervalo=intervalo)

@main.route('/get_time_interval')
@login_required
def get_time_interval():
    intervalo = obtener_intervalo()
    return jsonify(interval=intervalo)


@main.route('/updateUsers/<int:user_id>', methods=['GET', 'POST'])
@login_required
def updateUsers(user_id):
    user = obtener_usuario_por_id(user_id)
    if request.method == 'POST':
        form_data = request.form.to_dict()
        user_actualizado = actualizar_usuario(user_id, form_data)
        if user_actualizado:
            flash('Usuario actualizado exitosamente', 'success')
        else:
            flash('Error al actualizar el usuario', 'danger')
        return render_template('updateSucefull_users.html')
    return render_template('updateUsers.html', usuario=user)


@main.route('/delete_users/<int:user_id>', methods=['GET', 'POST'])
@login_required
def delete_users(user_id):
    user = obtener_usuario_por_id(user_id)
    if user:
        # Cambia el estado del user a "eliminado"
        user.status_id = '3'
        db.session.commit()
        flash('El usuario ha sido desactivado correctamente', 'success')
        return render_template('eliminado_user.html')
    else:
        flash('usuario no encontrada', 'danger')

    return redirect(url_for('main.dashboard'))


@main.route('/update_citas/<int:cita_id>', methods=['GET', 'POST'])
@login_required
def update_citas(cita_id):
    cita = obtener_cita_por_id(cita_id)
    if request.method == 'POST':
        form_data = request.form.to_dict()
        cita_actualizada = actualizar_cita(cita_id, form_data)
        if cita_actualizada:
            flash('Cita actualizada exitosamente', 'success')
        else:
            flash('Error al actualizar la cita', 'danger')
        return render_template('updateSucefull.html')
    return render_template('update_citas.html', cita=cita)

@main.route('/delete_citas/<int:cita_id>', methods=['GET', 'POST'])
@login_required
def delete_citas(cita_id):
    cita = Cita.query.get(cita_id)
    if cita:
        # Cambia el estado del cita a "eliminado"
        cita.status_id = '4'
        db.session.commit()
        flash('El doctor ha sido desactivado correctamente', 'success')
        return render_template('eliminado.html')
    else:
        flash('cita no encontrada', 'danger')

    return redirect(url_for('main.dashboard'))

app/templates/citas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Citas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6131ecdde6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/citas.css') }}">
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
    
    <div class="container_citas">
        <div class="table_cit">
            <div>
                <h1>Lista de Citas</h1>
            </div>
        <div class="table_citas">    
        <table class="table table-striped" id="appointment-table">
            <thead>
                <tr>
                    <th scope="col">Fecha de Creación</th>
                    <th scope="col">Última Modificación</th>
                    <th scope="col">Título de la Cita</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">ID del Paciente</th>
                    <th scope="col">Número de Autorización</th>
                    <th scope="col">Fecha de Inicio</th>
                    <th scope="col">Fecha Final</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for cita in citas.items %}
                <tr>
                    <td>{{ cita.date_created }}</td>
                    <td>{{ cita.last_modified }}</td>
                    <td>{{ cita.title }}</td>
                    <td>{{ cita.description }}</td>
                    <td>{{ cita.owner_id }}</td>
                    <td>{{ cita.status_label }}</td>
                    <td>{{ cita.start }}</td>
                    <td>{{ cita.end }}</td>
                    <td>
                        {% if cita.status_id == 1 %}
                            Reprogramada
                        {% elif cita.status_id == 2 %}
                            Asignada
                        {% elif cita.status_id == 3 %}
                            Cancelada
                        {% elif cita.status_id == 4 %}
                            eliminada
                        {% else %}
                            Desconocido
                        {% endif %}
                    </td>
                    <td class="accion"><a href="{{ url_for('main.update_citas', cita_id=cita.cita_id) }}"><i class="fa-solid fa-pen-to-square"></i></a> <a href="{{ url_for('main.delete_citas', cita_id=cita.cita_id) }}"><i class="fa-solid fa-trash" style="color: #ee2b2b;"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            {% if citas.has_prev %}
                <a href="{{ url_for('main.Con_Citas', page=1) }}"><i class="fa-solid fa-angles-left"></i></a>
                <a href="{{ url_for('main.Con_Citas', page=citas.prev_num) }}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}
            
            Página {{ citas.page }} de {{ citas.pages }}
            
            {% if citas.has_next %}
                <a href="{{ url_for('main.Con_Citas', page=citas.next_num) }}"><i class="fa-solid fa-arrow-right"></i></a>
                <a href="{{ url_for('main.Con_Citas', page=citas.pages) }}"><i class="fa-solid fa-angles-right"></i></a>
            {% endif %}
        </div>
    </div>
    </div>    
</div>
{% endblock %}
</body>
</html>

app/templates/formRegisAsesor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{{ url_for('main.reg_usuariosAses') }}" method="POST">
        <h1>Registro de Usuarios</h1>
        <div class="container_label">
          <div>
            <label for="username">Nombre de usuario</label><br>
            <input type="text" id="username" name="username" placeholder="Nombre de usuario" required><br>
      
            <label for="fname">Nombre</label><br>
            <input type="text" id="fname" name="fname" placeholder="Nombre" required><br>
            
            <label for="phone">Teléfono</label><br>
            <input type="text" id="phone" name="phone" placeholder="Teléfono" required><br>

            <label for="Password">Clave</label><br>
            <input type="password" id="Password" name="Password" placeholder="Password" required><br>
      
            <label for="position">Sucursal</label><br>
            <div class="input-container">
              <input type="text" id="position" name="position" placeholder="Cardio IB IPS" value="Cardio IB IPS" readonly>
            </div><br>
          </div>
          <div>
            <label for="email">Correo</label><br>
            <input type="email" id="email" name="email" placeholder="Correo" required><br>
      
            <label for="lname">Apellido</label><br>
            <input type="text" id="lname" name="lname" placeholder="Apellido" required><br>
      
            <label for="organization">RUT/CC</label><br>
            <input type="text" id="organization" name="organization" placeholder="RUT/CC" required><br>
            
            <label for="document_type">Tipo de documento</label><br>
            <input type="text" id="document_type" name="document_type" placeholder="Tipo de documento" required><br>
          </div>
        </div>
        <input type="submit" value="Enviar">
      </form>
</body>
</html>

app/templates/updateUsers.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Usuario</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles_form_usuario.css') }}">
</head>
<body>
    <div class="container">
        <form action="{{ url_for('main.updateUsers', user_id=usuario.user_id) }}" method="POST">
            <h1>Registro de Usuarios</h1>
            <div class="container_label">
              <div>
                <label for="username">Nombre de usuario</label><br>
                <input type="text" id="username" name="username" value="{{ usuario.username }}" required><br>
          
                <label for="fname">Nombre</label><br>
                <input type="text" id="fname" name="fname" value="{{ usuario.fname }}" required><br>
                
                <label for="phone">Teléfono</label><br>
                <input type="text" id="phone" name="phone" value="{{ usuario.phone }}" required><br>
          
              </div>
              <div>
                <label for="email">Correo</label><br>
                <input type="email" id="email" name="email" value="{{ usuario.email }}" required><br>
          
                <label for="lname">Apellido</label><br>
                <input type="text" id="lname" name="lname" value="{{ usuario.lname }}" required><br>
          
                <label for="organization">RUT/CC</label><br>
                <input type="text" id="organization" name="organization" value="{{ usuario.organization }}" required><br>
                
                <label for="document_type">Tipo de documento</label><br>
                <input type="text" id="document_type" name="document_type" value="{{ usuario.document_type }}" required><br>
              </div>
            </div>
            <input type="submit" value="Actualizar">
          </form>
    </div>
</body>
</html>

app/templates/update_citas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles_calendario.css') }}">
    <title>Actualizar Citas</title>
    
</head>
<body>
    <div class="container">
        <h1>Actualizar Cita</h1>
        <form method="post" action="{{ url_for('main.update_citas', cita_id=cita.cita_id) }}">
            <div class="form-container">
                <h2>Formulario de Registro de Citas</h2>
                <div id="appointment-form">
                    <div>
                        <h3>Detalles de la Cita</h3>
                        <label>Título de la cita</label><br><br>
                        <input type="text" id="title" name="title" value="{{ cita.title }}" readonly required><br>
                        <label>Descripción de la cita</label><br><br>
                        <input type="text" id="description" name="description" value="{{ cita.description }}" required><br>
                         <label>Fecha de inicio</label><br><br>
                        <input type="date" id="inicio-fecha" name="inicio_fecha" value="{{ cita.start.strftime('%Y-%m-%d') }}" readonly required>
                        <input type="time" id="inicio-hora" name="inicio_hora" value="{{ cita.start.strftime('%H:%M') }}" required><br><br>
                        <label>Fecha de fin</label><br><br>
                        <input type="date" id="fin-fecha" name="fin_fecha" value="{{ cita.end.strftime('%Y-%m-%d') }}" readonly required>
                        <input type="time" id="fin-hora" name="fin_hora" value="{{ cita.end.strftime('%H:%M') }}" required>
                        <p id="duracion">0 horas 0 minutos</p>
                        <label>Repetir</label><br><br>
                        <select name="repetir" class="selecc" required>
                            <option value="no" {% if cita.type_label == 'no' %}selected{% endif %}>No se repite</option>
                            <option value="diario" {% if cita.type_label == 'diario' %}selected{% endif %}>Diario</option>
                            <option value="semanal" {% if cita.type_label == 'semanal' %}selected{% endif %}>Semanal</option>
                            <option value="mensual" {% if cita.type_label == 'mensual' %}selected{% endif %}>Mensual</option>
                        </select><br>
                        <label>Recursos</label><br><br>
                        <select name="recursos" class="selecc" required>
                            <option value="MESA BASCULANTE B" {% if cita.recursos == 'MESA BASCULANTE B' %}selected{% endif %}>MESA BASCULANTE B</option>
                            <option value="Otro" {% if cita.recursos == 'Otro' %}selected{% endif %}>Otro</option>
                        </select><br>
                    </div>
                    <div>
                        <h3>Información del Paciente</h3>
                        <label>Nombre o Rut(CC)</label><br><br>
                        <input type="text" id="paciente" name="paciente" value="{{ cita.owner_id }}" required><br>
                        <table id="resultsTable" style="display:none;">
                            <tbody>
                                <!-- Los resultados se mostrarán aquí -->
                            </tbody>
                        </table>
                        <label>Edad del paciente</label><br><br>
                        <input type="number" name="edad" value="{{ cita.edad }}" min="18" max="100" required><br>
                        <label>Estado de la cita</label><br><br>
                        <select name="estado" class="selecc" required>
                            <option value="1" {% if cita.estado == 1 %}selected{% endif %}>Reprogramada</option>
                            <option value="2" {% if cita.estado == 2 %}selected{% endif %}>Asignada</option>
                            <option value="3" {% if cita.estado == 3 %}selected{% endif %}>Cancelada</option>
                        </select><br>
                        <label>Número de autorización</label><br><br>
                        <input type="text" name="autorizacion" value="{{ cita.status_label }}" required><br>
                        <label>El paciente requiere prioridad de atención</label><br><br>
                        <select name="prioridad" class="selecc" required>
                            <option value="no" {% if cita.prioridad == 'no' %}selected{% endif %}>No</option>
                            <option value="si" {% if cita.prioridad == 'si' %}selected{% endif %}>Sí</option>
                        </select><br>
                        <label>Registro en la llamada</label><br><br>
                        <select name="registro_llamada" class="selecc" required>
                            <option value="N" {% if cita.registro_llamada == 'N' %}selected{% endif %}>N</option>
                            <option value="S" {% if cita.registro_llamada == 'S' %}selected{% endif %}>S</option>
                        </select><br>
                        <label>¿Cuál?</label><br><br>
                        <input type="text" name="cual" value="{{ cita.cual }}" required><br>
                    </div>
                </div>
                <input type="submit" value="Actualizar">
            </div>
        </form>
    </div>     
         <script>
            console.log("{{ cita.start }}")
        $(document).ready(function(){
            $('#paciente').on('input', function(){
                let query = $(this).val();
                console.log('Input:', query); // Verifica el valor del input
                if(query.length > 2) {
                    $.ajax({
                        url: "{{ url_for('main.search_user') }}", // Asegúrate de que la URL es correcta
                        method: "GET",
                        data: { query: query },
                        success: function(data) {
                            console.log('Response:', data); // Verifica la respuesta del servidor
                            let results = data.results;
                            let tableBody = $('#resultsTable tbody');
                            tableBody.empty();

                            if(results.length > 0) {
                                $('#resultsTable').show();
                                results.forEach(function(user) {
                                    let row = `<tr class="selectable">
                                        <td>${user.fname} ${user.lname} (${user.organization})</td>   
                                    </tr>`;
                                    tableBody.append(row);
                                });

                                $('.selectable').on('click', function() {
                                    let selectedText = $(this).find('td').text(); // Assuming Rut(CC) is in the third column
                                    $('#paciente').val(selectedText);
                                    $('#resultsTable').hide();
                                });
                            } else {
                                $('#resultsTable').hide();
                            }
                        },
                        error: function(error) {
                            console.log('Error:', error);
                        }
                    });
                } else {
                    $('#resultsTable').hide();
                }
            });

            $('#citaForm').on('submit', function(event) {
                event.preventDefault(); // Evitar el envío del formulario estándar
                let paciente = $('#paciente').val(); // Obtener el valor del campo del paciente
                
                $.ajax({
                    url: "{{ url_for('main.reg_citas') }}",
                    method: "POST",
                    data: { paciente: paciente },
                    success: function(response) {
                        console.log('Formulario enviado exitosamente', response);
                        // Puedes agregar lógica adicional aquí, como mostrar un mensaje de éxito
                    },
                    error: function(error) {
                        console.log('Error al enviar el formulario', error);
                        // Puedes agregar lógica adicional aquí, como mostrar un mensaje de error
                    }
                });
            });
        });
    </script>
</body>
</html>

app/templates/usuarios.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Usuarios</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tablas_usuarios.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <script src="https://kit.fontawesome.com/6131ecdde6.js" crossorigin="anonymous"></script>
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
    <div class="container_users">
    <div class="tabla_us">
    <div>
        <h1>Lista de Usuarios</h1>
        </div>
        <div class="butt_acc">
    <div>
        <a href="{{ url_for('main.reg_usuarios') }}">Registrar pacientes</a><br>
        <a href="{{ url_for('main.reg_usuariosAses') }}">Registrar Usuarios</a>
        </div>
    <div>
        <!-- Campo de búsqueda -->
        <input type="text" id="searchInput" class="form-control mb-3" placeholder="Buscar usuarios...">    
        </div>
    </div>
    <div class="table_users">
        <table class="table table-striped" id="user-table">
            <thead>
                <tr>
                    <th scope="col">Nombre de Usuario</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Correo</th>
                    <th scope="col">Teléfono</th>
                    <th scope="col">RUT - CC</th>
                    <th scope="col">Fecha de creacion</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Accion</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in users.items %}
                <tr>
                    <td>{{ usuario.username }}</td>
                    <td>{{ usuario.fname }}</td>
                    <td>{{ usuario.lname }}</td>
                    <td>{{ usuario.email }}</td>
                    <td>{{ usuario.phone }}</td>
                    <td>{{ usuario.organization }}</td>
                    <td>{{ usuario.date_created }}</td>
                    <td>
                        {% if usuario.status_id == 1 %}
                            Activo
                        {% elif usuario.status_id == 2 %}
                            Esperando   
                        {% elif usuario.status_id == 3 %}
                            Inactivo
                        {% else %}
                            Desconocido
                        {% endif %}
                    </td>
                    <td class="accion"><a href="{{ url_for('main.updateUsers', user_id=usuario.user_id) }}"><i class="fa-solid fa-pen-to-square"></i></a> <a href="{{ url_for('main.delete_users', user_id=usuario.user_id) }}"><i class="fa-solid fa-trash" style="color: #ee2b2b;"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            {% if users.has_prev %}
                <a href="{{ url_for('main.usuarios', page=1) }}"><i class="fa-solid fa-angles-left"></i></a>
                <a href="{{ url_for('main.usuarios', page=users.prev_num) }}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}
            
            Página {{ users.page }} de {{ users.pages }}
            
            {% if users.has_next %}
                <a href="{{ url_for('main.usuarios', page=users.next_num) }}"><i class="fa-solid fa-arrow-right"></i></a>
                <a href="{{ url_for('main.usuarios', page=users.pages) }}"><i class="fa-solid fa-angles-right"></i></a>
            {% endif %}
        </div>
    </div>
</div>
</div>
    <script>
        document.getElementById('searchInput').addEventListener('keyup', function() {
            let input = this.value.toLowerCase();
            let table = document.getElementById('user-table');
            let rows = table.getElementsByTagName('tr');

            for (let i = 1; i < rows.length; i++) {
                let cells = rows[i].getElementsByTagName('td');
                let match = false;
                for (let j = 0; j < cells.length; j++) {
                    if (cells[j].innerText.toLowerCase().includes(input)) {
                        match = true;
                        break;
                    }
                }
                rows[i].style.display = match ? '' : 'none';
            }
        });
    </script>
    {% endblock %}
</body>
</html>